# This code will take a year by species matrix generated by neutral model,
# but only last 26 time steps
# compute tail dep matrix between years (so checks 
# if ranks of rare (or common) species remains consistent throughout the years)

source("tail_analysis.R")
source("compute_avg_cor.R")
#----------------------------------
library(tidyverse)
#--------------------------------------

taildep_neutral<-function(resloc_ta, resloc_input, nrep){
  
  # make output folder
  for(i in 1:nrep){
    k<-paste(resloc_ta,i,"/",sep="")
    if(!dir.exists(k)){
      dir.create(k)
    }
  }
  
  #------------ Now compute and plot the tail stats ---------------------
  for(i in 1:nrep){
    resloc_output<-paste(resloc_ta,i,"/",sep="")
    df<-paste(resloc_input,"yr_by_sp_nrep_",i,".RDS",sep="") # dataframe with species timeseries along column
    df<-readRDS(df)
    
    #----------- tail analysis with last 26 timeseries ----------------
    df<-tail(df, n =26)
    res<-tail_analysis(mat = df, resloc = resloc_output, nbin = 2)
    
    #----------------- compute avg correlation between years ---------------
    res2<-compute_avg_cor(mat=df)
    saveRDS(res2,paste(resloc_output,"avg_cor_metric.RDS",sep=""))
    
    cat("------ nrep = ", i," --------- \n")
  }
  
  #--------------------------------------------------------------------
}
###################################################





